[package]
name = "vulkano-util"
version = "0.34.1"
edition = "2021"
authors = ["The vulkano contributors"]
repository = "https://github.com/vulkano-rs/vulkano"
description = "Utility functionality to make usage of Vulkano easier"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/vulkano"
homepage = "https://vulkano.rs"
keywords = ["vulkan", "bindings", "graphics", "gpu", "rendering"]
categories = ["rendering::graphics-api"]

[dependencies]
ahash = "0.8"
vulkano = { version = "0.34.0", path = "../vulkano", default-features = false }
winit = { version = "0.30.4" }
